### ISSUE TITLE
Requested feature: Option to install missing packages without loading them

### ISSUE THREAD

**Issue by GitHunter0** [DesiQuintans/librarian#26]
@DesiQuintans , very often I just want to make sure the packages are installed but I do not want them loaded because it would pollute the namespace environment. Once the missing packages are installed, I like to access the packages functions via double colons `::` to avoid conflicting names. 

I have not found this valuable feature (at least for me) in any other package. Would you consider implementing that? 

Thank you. 

PS: Congratulations for the package, `librarian `is very useful.

**Comment by DesiQuintans** [comment]
Hi, it's already there! `librarian::check_installed()` and `librarian::check_attached()` can check whether a package is installed and/or attached. `librarian::check_installed()` will take some time to run when you call it the first time because it's searching all of your library paths, but the results get cached and subsequent runs will be near instant.

**Comment by GitHunter0** [comment]
Hey @DesiQuintans , thank you for the response. 
The issue is that those functions only check if the specified packages are installed, I would like one that also installs the missing packages.

**Comment by DesiQuintans** [comment]
Oh I see, you want something like shelf() that checks and installs packages, but does not automatically attach them. Yeah I can look at that.

**Comment by GitHunter0** [comment]
> Oh I see, you want something like shelf() that checks and installs packages, but does not automatically attach them. Yeah I can look at that.

Exactly! @DesiQuintans, I appreciate if you could implement something like that, it would be very useful to me.
